#!/bin/bash

CURR_LANG="$(setxkbmap -print | grep xkb_symbols | awk '{print $4}' | awk -F"+" '{print $2}')"
US="us"
HU="hu"

if [ $CURR_LANG == $US ]
then
	echo "US"
elif [ $CURR_LANG == $HU ]
then
	echo "HU"
else
	echo "--"
fi

# Click Actions
case "$BLOCK_BUTTON" in
    1) $SCRIPT_DIR/language & ;;    # left click
    3) $SCRIPT_DIR/language & ;;    # right click
esac
