#!/bin/bash

ACTIVE_WINDOW=$(xprop -id $(xprop -root _NET_ACTIVE_WINDOW | cut -d ' ' -f 5) WM_NAME | cut -d '"' -f 2)

if [[ "${ACTIVE_WINDOW}" != "" ]]; then
  echo "${ACTIVE_WINDOW}"
  echo "${ACTIVE_WINDOW}"
#  echo ""
fi

case "$BLOCK_BUTTON" in
    1) rofi -show window & ;;	#left click
    3) rofi -combi-modi window,drun,run -show combi -modi combi & ;;		#right click

esac
